config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#home'
  devise_for :users
  resources :users

  get 'workshops' => 'visitors#workshops'
  get 'planning' => 'visitors#planning'
  get 'prices' => 'visitors#pass'
  get 'teachers' => 'visitors#teachers'
  get 'edition_2015' => 'visitors#edition_2015'
  get 'hotel' => 'visitors#hotel'
  get 'test_mailchimp' => 'visitors#test_mailchimp'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
 
	def set_locale
	  I18n.locale = params[:locale] || I18n.default_locale
	end

	def default_url_options(options = {})
	    logger.debug "default_url_options is passed options: #{options.inspect}\n"
	    { :locale => I18n.locale }
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def home
	end

	def workshops
	end

	def planning
	end

	def pass
	end

	def teachers
	end

	def hotel
	end

	def edition_2015
	end

	def test_mailchimp
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>


<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png", :size => "150x60"), root_path %>
      
    </div>
    
      <span class="navbar-text"><i><%= t("season") %></i></span>
  
    <div class="collapse navbar-collapse navbar-right">

      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>

</nav> 

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<!--
=======
>>>>>>> 863e068b55d5c5c215497e4b0bba4e4ec6ef3980
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>
<<<<<<< HEAD
-->


<li><%= link_to t("home.menu"), root_path %></li>
<li><%= link_to t("teachers.menu"), teachers_path %></li>
<li><%= link_to t("workshops.menu"), workshops_path %></li>
<li><%= link_to t("hotel.menu"), hotel_path %></li>
<li><%= link_to t('pass.menu'), prices_path %></li>
<li><%= link_to t("edition_2015.menu"), edition_2015_path %></li>

<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    <%= t("language") %> <span class="caret"></span>
  </a>
	<ul class="dropdown-menu">
    <li><%= link_to t("FR"), url_for(:locale => 'fr') %></li>
    <li><%= link_to t("EN"), url_for(:locale => 'en') %></li>
  </ul>
</li>

<li>
  <form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be/"><input class="btn btn-primary navbar-btn" type="submit" value="<%= t("signup") %>"></form>
</li>
<!-- <li><%= button_to "Inscriptions", root_path(:anchor => 'subscribe'), class: "btn btn-primary navbar-btn", :method => :get %></li> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title><%= content_for?(:title) ? yield(:title) : "Swingplicity Brussels" %></title>
    
    <meta name="description" content="<%= t("description") %>">
    <meta name="keywords" content="<%= t("keywords") %>">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <!-- <main role="main">
    </main> -->
    <%= render 'layouts/messages' %>  
    <%= yield %>


    <!-- Modal accessible de partout dans l'application -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t("signup_title") %></h4>
      </div>
      <div class="modal-body">
        <%= render "visitors/test_mailchimp" %>
      </div>
      
    </div>
  </div>
</div>
  </body>
  <footer>
      <nav class="navbar navbar-inverse text-center footer-nav" role="navigation">
        <p>COPYRIGHT (C) 2018 BRUSSELS WCS ASBL</p>
        <p>Webdesign : <%= link_to "App' Strat' Gram'", "http://linkedin.com/in/laetitiamassa", :target => "_blank" %></p>
        <p><small>Crédits photographiques : 
          <%= link_to "François Brouckaert", "https://www.flickr.com/photos/franom/", :target => "_blank" %>,
           Denis Belekian, 
           Emeline Rochefeuille, 
          <%= link_to "Anja Klaucke", "http://finallymoving.com", :target => "_blank", :class => "courtesy" %>

        </small></p>
        
        <span class="fa-stack fa-lg">
          <a href="https://www.facebook.com/events/238048386528460/" target="_blank">
              <i class="fa fa-circle fa-stack-2x swingcolor"></i>
              <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
          </a>
        </span>

        <span class="fa-stack fa-lg">
          <a href="mailto:info@swingplicitybrussels.be" target="_blank">
              <i class="fa fa-circle fa-stack-2x swingcolor"></i>
              <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
          </a>
        </span>
      </nav>

  </footer>
</html>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/_early_bird.html.erb
<div class="row text-center">
    <div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level1">
					<h1 class="panel-title panel-title-landing">
						Gaston
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_1") %>
					</h2>
				</div>
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
						<tr>
							<td width="50px">&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
                    </table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2018-11-01 00:00:00 +0200" %>
						<input class="btn btn-price btn-lg btn-level1 disabled" type="submit" value="40 EUR">
						<% else %>
						<input class="btn btn-price btn-lg btn-level1" type="submit" value="40 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level2">
					<h1 class="panel-title panel-title-landing">
						Spirou
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_2") %>
					</h2>
				</div>
				
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 5,5h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_all") %> - 1h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2018-11-01 00:00:00 +0200" %>
						<input class="btn btn-price btn-level2 btn-lg disabled" type="submit" value="110 EUR">
						<% else %>
						<input class="btn btn-price btn-level2 btn-lg" type="submit" value="110 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level3">
					<h1 class="panel-title panel-title-landing">
						Tintin
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_3") %>
					</h2>
				</div>
			   
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 5,5h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_all") %> - 1h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2018-11-01 00:00:00 +0200 00:00:00 +0200" %>
						<input class="btn btn-price btn-level3 btn-lg disabled" type="submit" value="110 EUR">
						<% else %>
						<input class="btn btn-price btn-level3 btn-lg" type="submit" value="110 EUR">
						<% end %>
						</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level4">
					<h1 class="panel-title panel-title-landing">
						Marsupilami
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_4") %>
					</h2>
				</div>
			   
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 5,5h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_all") %> - 1h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2018-11-01 00:00:00 +0200" %>
						<input class="btn btn-price btn-level4 btn-lg disabled" type="submit" value="110 EUR">
						<% else %>
						<input class="btn btn-price btn-level4 btn-lg" type="submit" value="110 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level5">
					<h1 class="panel-title panel-title-landing">
						Lucky Luke
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_5") %>
					</h2>
				</div>
			   
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 5,5h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_all") %> - 1h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2018-11-01 00:00:00 +0200" %>
						<input class="btn btn-price btn-level5 btn-lg disabled" type="submit" value="110 EUR">
						<% else %>
						<input class="btn btn-price btn-level5 btn-lg" type="submit" value="110 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-extra">
					<h1 class="panel-title panel-title-landing">
						Relax Pass
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_extra") %>
					</h2>
				</div>
			   
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_extra_friday") %><br>1 H</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %><br>2 H</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2018-11-01 00:00:00 +0200" %>
						<input class="btn btn-price btn-extra btn-lg disabled" type="submit" value="40 EUR">
						<% else %>
						<input class="btn btn-price btn-extra btn-lg" type="submit" value="40 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/visitors/_later_bird.html.erb
<div class="row text-center">
    <div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level1">
					<h1 class="panel-title panel-title-landing">
						Gaston
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_1") %>
					</h2>
				</div>
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
						<tr>
							<td width="50px">&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
                    </table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2019-01-18 00:00:00 +0200" %>
						<input class="btn btn-price btn-lg btn-level1 disabled" type="submit" value="50 EUR">
						<% else %>
						<input class="btn btn-price btn-lg btn-level1" type="submit" value="50 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level2">
					<h1 class="panel-title panel-title-landing">
						Spirou
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_2") %>
					</h2>
				</div>
				
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 5,5h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_all") %> - 1h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2019-01-18 00:00:00 +0200" %>
						<input class="btn btn-price btn-level2 btn-lg disabled" type="submit" value="140 EUR">
						<% else %>
						<input class="btn btn-price btn-level2 btn-lg" type="submit" value="140 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level3">
					<h1 class="panel-title panel-title-landing">
						Tintin
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_3") %>
					</h2>
				</div>
			   
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 5,5h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_all") %> - 1h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2019-01-18 00:00:00 +0200 00:00:00 +0200" %>
						<input class="btn btn-price btn-level3 btn-lg disabled" type="submit" value="140 EUR">
						<% else %>
						<input class="btn btn-price btn-level3 btn-lg" type="submit" value="140 EUR">
						<% end %>
						</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level4">
					<h1 class="panel-title panel-title-landing">
						Marsupilami
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_4") %>
					</h2>
				</div>
			   
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 5,5h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_all") %> - 1h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2019-01-18 00:00:00 +0200" %>
						<input class="btn btn-price btn-level4 btn-lg disabled" type="submit" value="140 EUR">
						<% else %>
						<input class="btn btn-price btn-level4 btn-lg" type="submit" value="140 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-level5">
					<h1 class="panel-title panel-title-landing">
						Lucky Luke
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_level_5") %>
					</h2>
				</div>
			   
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses") %> - 5,5h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %> - 2h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_all") %> - 1h</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2019-01-18 00:00:00 +0200" %>
						<input class="btn btn-price btn-level5 btn-lg disabled" type="submit" value="140 EUR">
						<% else %>
						<input class="btn btn-price btn-level5 btn-lg" type="submit" value="140 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-4" style="margin-top: 20px;">
		<div class="pricing-table">
			<div class="panel panel-primary" style="border: none;">
				<div class="controle-header panel-heading panel-heading-landing-extra">
					<h1 class="panel-title panel-title-landing">
						Relax Pass
					</h1>
					<h2 class="panel-h2-pass">
						<%= t("pass.courses_extra") %>
					</h2>
				</div>
			   
				<div class="panel-body panel-body-landing">
					<table class="table">
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.courses_extra_friday") %><br>1 H</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.other_dance") %><br>2 H</td>
						</tr>
						<tr>
							<td width="50px"><i class="fa fa-check"></i></td>
							<td><%= t("pass.3_parties") %></td>
						</tr>
					</table>
				</div>
				<div class="panel-footer panel-footer-landing">
					<form class="button_to" method="get" target="_blank" action="http://registration.swingplicitybrussels.be">
						<% if Time.now > "2019-01-18 00:00:00 +0200" %>
						<input class="btn btn-price btn-extra btn-lg disabled" type="submit" value="50 EUR">
						<% else %>
						<input class="btn btn-price btn-extra btn-lg" type="submit" value="50 EUR">
						<% end %>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/visitors/_test_mailchimp.html.erb
	<embed src="https://docs.google.com/forms/d/1KTizegRN2aLlNbfhZ5WRmaYztzfORqVzUTYND3Y0Xo0/viewform" width="100%" height="500px" />

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

app/views/visitors/planning.html.erb
<div class="planning_bg">
	
</div>